update OCCA + add bw benchmark

diff --git a/3rdParty/occa/tests/run_examples b/3rdParty/occa/tests/run_examples
--- a/3rdParty/occa/tests/run_examples
+++ b/3rdParty/occa/tests/run_examples
@@ -1,5 +1,4 @@
 #!/bin/bash
-set -e
 
 OCCA_DIR=$(cd $(dirname "$0")/.. && pwd)
 EXAMPLE_DIR="${OCCA_DIR}/examples"
@@ -9,6 +8,9 @@ ASAN_OPTIONS+=':protect_shadow_gap=0'
 ASAN_OPTIONS+=':detect_container_overflow=0'
 
 HEADER_CHARS=80
+
+export LD_LIBRARY_PATH="${OCCA_DIR}/lib:${LD_LIBRARY_PATH}"
+export DYLD_LIBRARY_PATH="${OCCA_DIR}/lib:${DYLD_LIBRARY_PATH}"
 
 declare -a examples=(
   cpp/01_add_vectors
@@ -20,12 +22,15 @@ declare -a examples=(
   cpp/07_dtypes
   cpp/08_arrays
   cpp/09_streams
+  cpp/11_native_cpp_kernels
+  cpp/12_native_c_kernels
   c/01_add_vectors
   c/02_background_device
   c/03_inline_okl
   c/04_reduction
 )
 
+failed_examples=""
 for mode in $("${OCCA_DIR}/bin/occa" modes); do
     case "${mode}" in
         Serial) device="mode: 'Serial'";;
@@ -36,38 +41,61 @@ for mode in $("${OCCA_DIR}/bin/occa" modes); do
     esac
 
     for example_dir in "${examples[@]}"; do
-        # OpenCL throws CL_DEVICE_MAX_WORK_GROUP_SIZE
-        if [ -n "${TRAVIS}" ] && [ "${mode}" == "OpenCL" ]; then
-            continue
-        fi
+        flags=(--verbose --device "${device}")
 
-        # OpenCL + Shared memory is finicky
-        if [ "${mode}" == OpenCL ]; then
-            case "${example_dir}" in
-                cpp/04_reduction) continue;;
-                cpp/06_arrays) continue;;
-                c/03_reduction) continue;;
-            esac
-        fi
+        # Filters
+        case "${example_dir}" in
+            # OpenCL + Shared memory is finicky
+            # OpenCL throws CL_DEVICE_MAX_WORK_GROUP_SIZE
+            cpp/04_reduction)
+                if [[ "${mode}" == OpenCL ]]; then
+                    continue
+                fi;;
+            cpp/08_arrays)
+                if [[ "${mode}" == OpenCL ]]; then
+                    continue
+                fi;;
+            c/04_reduction)
+                if [[ "${mode}" == OpenCL ]]; then
+                    continue
+                fi;;
+            cpp/11_native_cpp_kernels)
+                if [[ "${mode}" != Serial ]]; then
+                    continue
+                fi
+                flags=(--verbose)
+                ;;
+            cpp/12_native_c_kernels)
+                if [[ "${mode}" != Serial ]]; then
+                    continue
+                fi
+                flags=(--verbose)
+                ;;
+        esac
 
         banner="(${mode}) ${example_dir}"
-        chars=$(echo "${banner}" | wc -c);
-        linechars=$((${HEADER_CHARS} - ${chars} - 6));
-	      line=$(printf '%*s' ${linechars} | tr ' ' '-');
-	      echo -e "\n---[ ${banner} ]${line}";
+        chars=$(echo "${banner}" | wc -c)
+        linechars=$((${HEADER_CHARS} - ${chars} - 6))
+	      line=$(printf '%*s' ${linechars} | tr ' ' '-')
+	      echo -e "\n---[ ${banner} ]${line}"
 
         cd "${EXAMPLE_DIR}/${example_dir}"
-        rm -rf main
-        make
+        make clean; make
 
-        # Make sure not to go over the log size
-        if [ -n "${TRAVIS}" ]; then
-            OCCA_VERBOSE=1 ./main --verbose --device "${device}" 2>&1 | head -n 100;
-        else
-            OCCA_VERBOSE=1 ./main --verbose --device "${device}" 2>&1
+        ./main "${flags[@]}"
+
+        # Check for example failures
+        if [ $? -ne 0 ]; then
+            failed_examples+="  - ${mode}: ${example_dir}\n"
         fi
 
         # Test output footer
-	      printf '%*s\n' ${HEADER_CHARS} | tr ' ' '=';
+	      printf '%*s\n' ${HEADER_CHARS} | tr ' ' '='
     done
 done
+
+if [[ "${failed_examples}" != "" ]]; then
+    echo -e "\n\nFailed examples:"
+    echo -e "${failed_examples}"
+    exit 1
+fi
